services:
  - type: web
    name: randimusic
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python -m __main__
    envVars:
      - key: PIP_NO_BUILD_ISOLATION
        value: true
      - key: PIP_USE_FEATURE
        value: "fast-deps"
    hooks:
      postDeploy:
        - apt-get update && apt-get install -y ffmpeg git
