services:
  - type: web
    name: randimusic
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-build-isolation --no-cache-dir -r requirements.txt
    startCommand: python -m __main__
    envVars:
      - key: PIP_NO_BUILD_ISOLATION
        value: true
    hooks:
      postDeploy:
        - apt-get update && apt-get install -y ffmpeg git
